default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: database_backend_development

test:
  <<: *default
  database: database_backend_test

production:
  <<: *default
  database: database_backend_production
  username: database_backend
  password: <%= ENV["DATABASE_BACKEND_DATABASE_PASSWORD"] %>
